server {
    listen 80;
    server_name monitoring.little-room.co.uk;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name monitoring.little-room.co.uk;

    ssl_certificate     /etc/letsencrypt/live/monitoring.little-room.co.uk/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/monitoring.little-room.co.uk/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    resolver 127.0.0.11 valid=10s;

    location / {
        set $upstream http://monitoring-grafana:3000;
        proxy_pass         $upstream;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
