server {
    listen 80;
    server_name monitoring.little-room.co.uk;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}
